language: node_js
node_js: stable
sudo: false
script:
  - npm test
install:
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  repo: katydecorah/staging
after_success:
  - npm run lh -- https://katydecorah.com/staging/
env:
  global:
    secure: Qc/8WtVGvVr/Y+LaxolHkZnxvnihWyAsiILKxw3BSr0uug84IbOrg89pFYO8jJII7vvQrhfv6UboaGPFkfGr2CoD6hQi5ZW0DpOaD0zDEcI9FhcHpH7M2hVaJOkLXKJEJigIlp2sHwxlIc9rPQFEh3Yn9GCRurXyuZDrzPUnzP8=
