language: node_js
node_js: stable
sudo: false
script:
  - npm test
before_install: gem update bundler

install:
  - gem install bundler
  - bundle install
  - npm install
after_success:
  - "./bin/deploy.sh"
  #- npm run lh -- https://staging.katydecorah.com
env:
  global:
    secure: Qc/8WtVGvVr/Y+LaxolHkZnxvnihWyAsiILKxw3BSr0uug84IbOrg89pFYO8jJII7vvQrhfv6UboaGPFkfGr2CoD6hQi5ZW0DpOaD0zDEcI9FhcHpH7M2hVaJOkLXKJEJigIlp2sHwxlIc9rPQFEh3Yn9GCRurXyuZDrzPUnzP8=
