name: Accessibility scan

on:
  pull_request:
    paths:
      - "**.md"

jobs:
  build:
    name: Scan site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: npm install @octokit/action@5.0.2 @actions/core@1.10.0

      - run: node .github/actions/pr-files.js
        id: files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}

      - name: Build site
        run: bundle exec jekyll build

      - run: npx serve _site &

      - name: Scan site
        uses: double-great/accessibility-scan-action@v0.3.0
        with:
          url: "http://localhost:3000"
          inputUrls: ${{ steps.files.outputs.InputUrls }}
          baselineFile: ${{ github.workspace }}/baselines/site.baseline
          maxUrls: ${{ steps.files.outputs.MaxUrls }}

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: "Accessibility report"
          path: ${{ github.workspace }}/_accessibility-reports/
