name: Accessibility scan

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install @octokit/action @actions/core
      # Node.js script can be anywhere. A good convention is to put local GitHub Actions
      # into the `.github/actions` folder
      - run: node .github/actions/pr-files.js
        id: files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{ github.event.pull_request.number }}

      - name: Build site
        run: bundle exec jekyll build

      - run: npx serve _site &

      - name: Scan site
        uses: double-great/accessibility-scan-action@input-urls
        with:
          url: "http://localhost:3000"
          inputUrls: ${{ steps.files.outputs.InputUrls }}
          baselineFile: ${{ github.workspace }}/baselines/site.baseline

      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: "Accessibility report"
          path: ${{ github.workspace }}/_accessibility-reports/
