name:  Accessibility Insights report

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Run Accessibility Insights
        uses: microsoft/accessibility-insights-action@v3
        with:
          static-site-dir: ${{ github.workspace }}/_site
      - name: Upload Accessibility Insights report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
