name: Accessibility scan

on:
  workflow_dispatch: # enable run button on github.com
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build site
        run: bundle exec jekyll build

      - run: npx serve _site &

      - name: Scan site
        uses: double-great/accessibility-scan-action@v0.1.0
        with:
          url: "http://localhost:3000"
          baselineFile: ${{ github.workspace }}/baseline/site.baseline

      - name: Upload Accessibility Insights report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-reports
          path: ${{ github.workspace }}/_accessibility-reports
