name: Add to recipe box
on:
  issues:
    types: opened

jobs:
  update_recipe:
    runs-on: macOS-latest
    name: Add recipe
    # only continue if issue has "recipe" label
    if: contains( github.event.issue.labels.*.name, 'recipe')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Recipe box
        uses: katydecorah/recipe-box-action@v1
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "Updated _data/recipes.yml"
          git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}
      - name: Close issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: "${{ env.IssueNumber }}"
          comment: "You made ${{ env.RecipeTitle }} on ${{env.DateCooked}}."
