name: Seasonal post

on:
  schedule:
    - cron: "00 02 20 Mar,Jun,Sep,Dec *"
  workflow_dispatch: # enables run button on github.com

jobs:
  seasonal_post:
    runs-on: ubuntu-latest
    name: Write seasonal post
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write seasonal post
        uses: katydecorah/seasonal-post-action@v5.2.1
        with:
          GitHubUsername: katydecorah
          GitHubRepository: has
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Commit files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "${{ env.season }}"
          git push
