name: Seasonal post

on:
  schedule:
    - cron: "00 02 20 Mar,Jun,Sep,Dec *"
  workflow_dispatch:
    inputs:
      date:
        description: Set a specific date to run the action (YYYY-MM-DD), leave blank for today.
        type: string

jobs:
  seasonal_post:
    runs-on: ubuntu-latest
    name: Write seasonal post
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write seasonal post
        uses: katydecorah/seasonal-post-action@v6.2.1
        with:
          github-username: katydecorah
          github-repository: archive
          source-bookmarks: recipes|_data/recipes.json
          seasonal-post-template: .github/actions/seasonal-post-template.md
          book-tags: "recommend, skip, content warning"
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Commit files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m "${{ env.seasonEmoji }} ${{ env.season }}"
          git push
